@startuml
left to right direction
skinparam shadowing false

actor Клиент as us1
actor Администратор as admin
actor Тренер as trener

usecase "Регистрация" as reg
usecase "Смотреть информацию о клубе" as watch
usecase "Оплата услуг" as pay
usecase "Оценка занятий" as assess
usecase "Запись на занятие" as sign
usecase "Ведение клиентской базы" as con
usecase "Просмотр информации о клиентах" as info
usecase "Добавление пользователя" as add
usecase "Удаление пользователя" as del

us1 -- reg
us1-- watch
us1 -- pay
us1 -- assess
us1 -- sign

admin -- pay
admin -- assess
admin -- con
admin -- info

con .up.|> add
con .up.|> del
admin <|-- trener
@enduml
